version: "0.1"
environments:
  - name: master
    branch: master
    mode: pull-request
apps:
  - name: Angular Realworld Example App
    path: ""
    text-resources:
      - path: src/*.html
        format: angular-hardcoded
