# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool: 'laptops'

variables:
  dockerImageName: 'pipeline-app'  # Docker image name (you can adjust this)
  dockerRegistryServiceConnection: 'https://hub.docker.com'  # Replace with your Docker registry service connection
  imageTag: 'nginx:latest'  # Tag for the Docker image

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: | 
    npm install 
    npm install -g @angular/cli
    npm run build
  displayName: 'npm install and build'








