# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool: 'laptops'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: | 
    npm install 
    npm install -g @angular/cli
    npm run build
  displayName: 'npm install and build'

- script: |   
    docker build -t my-react-app -f ./Dockerfile .
    docker images
    docker run -d -p 8080:80 my-react-app

  displayName: 'Build and run Docker image'













