# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool: 'laptops'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: | 
    npm install 
    npm install -g @angular/cli
    npm run build
  displayName: 'npm install and build'

- script: |
    curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
  displayName: 'Install Azure CLI'

- script: |
    docker build -t my-react-app -f ./Dockerfile .
    docker images
    az acr login --name azregistry  # Login to Azure Container Registry
    docker tag my-react-app:latest azregistry.azurecr.io/my-react-app:latest
    docker push azregistry.azurecr.io/my-react-app:latest
    docker run -d -p 8081:80 my-react-app
  displayName: 'Build, tag, and push Docker image to ACR'

















