trigger:
- main

pool: 'laptops'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install 
    npm install -g @angular/cli
    npm run build
  displayName: 'npm install and build'

- script: |
    docker build -t my-react-app -f ./Dockerfile .
    docker images
    az acr login --name azregistry
    docker tag my-react-app:latest azregistry.azurecr.io/my-react-app:latest
    docker push azregistry.azurecr.io/my-react-app:latest
    docker run -d -p 8080:80 my-react-app
  displayName: 'Build, tag, and push Docker image to ACR'

- bash: |
    echo "Updating deployment.yaml with the correct image tag..."
    sed -i "s|image: azregistry.azurecr.io/my-react-app:.*|image: azregistry.azurecr.io/my-react-app:latest|" Deployment.yaml
    cat Deployment.yaml
  displayName: 'Update Deployment YAML with correct image tag'

- bash: |
    echo "Deploying Kubernetes resources..."
    kubectl apply -f Deployment.yaml --validate=false
    kubectl apply -f service.yaml --validate=false
  displayName: 'Deploy Kubernetes Deployment and Service'



















