apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-react-app
  template:
    metadata:
      labels:
        app: my-react-app
    spec:
      containers:
        - name: my-react-app
          image: azregistry.azurecr.io/my-react-app:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-react-app-service
spec:
  selector:
    app: my-react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-react-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - parties.p.frii.site
    secretName: parties-tls  
  rules:
  - host: parties.p.frii.site
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-react-app-service  
            port:
              number: 80

---
apiVersion: v1
kind: Secret
metadata:
  name: indians-tls 
  namespace: default
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURpVENDQXc2Z0F3SUJBZ0lTQlBxK1kwN2RjM05zYTlnR3prTkllWExjTUFvR0NDcUdTTTQ5QkFNRE1ESXgKQ3pBSkJnTlZCQVlUQWxWVE1SWXdGQVlEVlFRS0V3MU1aWFFuY3lCRmJtTnllWEIwTVFzd0NRWURWUVFERXdKRgpOakFlRncweU5UQXhNamN4TURVMk16aGFGdzB5TlRBME1qY3hNRFUyTXpkYU1CNHhIREFhQmdOVkJBTVRFM0JoCmNuUnBaWE11Y0M1bWNtbHBMbk5wZEdVd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFRVDJ0My8KRWF2OFlhaDM1SjhucmQ2QkhuWU1wZm1rbDg4MWk0bEFTV1U2U1BHdVJlWVlDYjhLTnIxWll1RlZTdVoxU0tvUgpxQWtVNTN3VWgrWWhBOFpybzRJQ0ZqQ0NBaEl3RGdZRFZSMFBBUUgvQkFRREFnZUFNQjBHQTFVZEpRUVdNQlFHCkNDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJTZ2VHYncKMUUxSWJYUzZneHVYR2RQY1F5eDd3REFmQmdOVkhTTUVHREFXZ0JTVEowYVlBNmxSYUk2WTFzUkNTTnNqdjFpVQowakJWQmdnckJnRUZCUWNCQVFSSk1FY3dJUVlJS3dZQkJRVUhNQUdHRldoMGRIQTZMeTlsTmk1dkxteGxibU55CkxtOXlaekFpQmdnckJnRUZCUWN3QW9ZV2FIUjBjRG92TDJVMkxta3ViR1Z1WTNJdWIzSm5MekFlQmdOVkhSRUUKRnpBVmdoTndZWEowYVdWekxuQXVabkpwYVM1emFYUmxNQk1HQTFVZElBUU1NQW93Q0FZR1o0RU1BUUlCTUlJQgpCUVlLS3dZQkJBSFdlUUlFQWdTQjlnU0I4d0R4QUhjQW91TUs1RVh2dmEyYmZqanRSMmQzVTllQ1c0U1UxeXRlCkd5ekV1VkNrUitjQUFBR1VwNTJRWEFBQUJBTUFTREJHQWlFQWh4Z3A0V2RpQ2hwdU51T2cvSWRFK3lBaHJmem4KS2Y0SHB4ZGtHUnlqVWVNQ0lRQ09RUlhsc2pmTnJ4SitPdXViZHhrYnBjc0E4WWw3eDZvNENiM0N0ckJZYXdCMgpBTThSVnU3VkxueXY4NGRiMldrdW0ra2FjV2RLc0Jmc3JBSFNXM2ZPekRzSUFBQUJsS2Vka0lFQUFBUURBRWN3ClJRSWdJWkpqOWRwc0pUZ2xmTHl4VnVWZkNVTGE2WkJ5S3htUjJBU0d1RWFhK0FrQ0lRRHMvTUxKbTNkSjIwbVIKZDJ3RjZMbkxZUjVVOU5vTHFSUGp6L3VsTmJVWlJUQUtCZ2dxaGtqT1BRUURBd05wQURCbUFqRUFtQ25mSUN1awp0d09VUytPOWM1YzVWN3VkOHFKQ3lQSHBrMVFkbEx6ZS90RTRjUDE3QmpUUEIrVitpZ2Fyc01yY0FqRUFnNGhlClE3TjZaZjVOSlFXOVlzWG5tSDl1UUJ3dm43dTljVVBqdzZNWjNQS3o2VnhCT0FjZ1JYQy9xdzl0d3dERQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlFVnpDQ0FqK2dBd0lCQWdJUkFMQlhQcEZ6bHlkdzI3U0h5enBGS3pnd0RRWUpLb1pJaHZjTkFRRUxCUUF3ClR6RUxNQWtHQTFVRUJoTUNWVk14S1RBbkJnTlZCQW9USUVsdWRHVnlibVYwSUZObFkzVnlhWFI1SUZKbGMyVmgKY21Ob0lFZHliM1Z3TVJVd0V3WURWUVFERXd4SlUxSkhJRkp2YjNRZ1dERXdIaGNOTWpRd016RXpNREF3TURBdwpXaGNOTWpjd016RXlNak0xT1RVNVdqQXlNUXN3Q1FZRFZRUUdFd0pWVXpFV01CUUdBMVVFQ2hNTlRHVjBKM01nClJXNWpjbmx3ZERFTE1Ba0dBMVVFQXhNQ1JUWXdkakFRQmdjcWhrak9QUUlCQmdVcmdRUUFJZ05pQUFUWjhaNUcKaC9naGNXQ29KdXVqK3JucTJoMjVFcWZVSnRsUkZMRmhmSFdXdnlJTE9SL1Z2dEVLUnFvdFBFb0poQzYrUUpWVgo2UmxBTjJaMTdUSk9kd1JKK0hCN3d4am56dmR4RVA2c2ROZ0ExTzF0SEhNV014Q2NPckxxYkdMMHZiaWpnZmd3CmdmVXdEZ1lEVlIwUEFRSC9CQVFEQWdHR01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0QKQVRBU0JnTlZIUk1CQWY4RUNEQUdBUUgvQWdFQU1CMEdBMVVkRGdRV0JCU1RKMGFZQTZsUmFJNlkxc1JDU05zagp2MWlVMGpBZkJnTlZIU01FR0RBV2dCUjV0Rm5tZTdibDVBRnpnQWlJeUJwWTl1bWJiakF5QmdnckJnRUZCUWNCCkFRUW1NQ1F3SWdZSUt3WUJCUVVITUFLR0ZtaDBkSEE2THk5NE1TNXBMbXhsYm1OeUxtOXlaeTh3RXdZRFZSMGcKQkF3d0NqQUlCZ1puZ1F3QkFnRXdKd1lEVlIwZkJDQXdIakFjb0JxZ0dJWVdhSFIwY0RvdkwzZ3hMbU11YkdWdQpZM0l1YjNKbkx6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FnRUFmWXQ3U2lBMXNnV0dDSXB1bms0NnI0QUV4SVJjCk14a0tnVWhObHJydjFCMjFoT2FYTi81bWlFK0xPVGJyY21VL005eXZDNk1WWTczMEdORm9MOEloSjhqOHZyT0wKcE1ZMjJPUDZiYVMxazlZTXJ0RFRsd0pIb0dieTA0VGhUVWVCRGtzUzlSaXVIdmljWnFCZWRRZElGNjVwWnVocAplRGNHQmNMaVlhc1FyL0VPNWd4eHRMeVRtZ3NIU09WU0JjRk9uOWxndjdMRUNQcTlpN21mSDNtcHhnclJLU3hICnBPb1owS1hNY0IraEh1dmxrbEhudHZjSTBtTU1RMG1oWWo2cXRNRlN0a0YxUnBDRzNJUGRJd3BWQ1FxdThHVjcKczh1YmtuUnpzKzNDL0JtMTlSRk9vaVBwRGt3dnlOZnZtUTE0WGt5cXFLSzVvWjh6aEQzMmtGUlFreGE4dVpTdQpoNGFUSW1GeGtudTM5d2FCeElSWEU0akt4bEFtUWM0UWpGWm9xMUttUXFRZzBKLzFKRjhSbEZ2SmFzMVZjakx2CllsdlVCMnQ2bnBPNm9RakIzbCtQTmYwRHBRSDdpVXgzV3o1QWpRQ2k2TDI1Rmp5RTA2cTZCWi9RbG10WWRsLzgKWllhbzRTUnFQRXMvNmNBaUYrUWY1emcyVWthV3REcGhsMUxLTXVUTkxvdHZzWDk5SFA2OVYyZmFOeWVnb2RRMApMeVRBcHIvdlQwMVlQRTQ2dk5zRExnSys0Y0w2VHJ6Qy9hNFdjbUY1U1JKOTM4enJ2L2R1SkhMWFFJa3U1djArCkV3T3k1OUhkbTBQVC9Fci84NGREVjBDU2pkUi8yWHVaTTNrcHlzU0tMZ0QxY0tpREErSVJndU9EQ3hmTzljeVkKSWc0NnY5bUZtQnZ5SDA0PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUdDSnlydUZxUnhUZHkxb1JqS0hPdnlqOFFqZzhmVnVKLzNVQUVWaHNTTVBvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFRTlyZC94R3IvR0dvZCtTZko2M2VnUjUyREtYNXBKZlBOWXVKUUVsbE9ranhya1htR0FtLwpDamE5V1dMaFZVcm1kVWlxRWFnSkZPZDhGSWZtSVFQR2F3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQ
